name: .NET Core Desktop

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Install MSBuild
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore dependencies
      run: dotnet restore

    - name: Build the application
      run: msbuild BookOrca.sln /p:Configuration=Release

    - name: Run unit tests
      run: dotnet test BookOrca.TestProjects/BookOrca.DataAccess.Test/BookOrca.DataAccess.Test.csproj

    - name: Package the application
      run: msbuild BookOrca/BookOrca/BookOrca.csproj /p:Configuration=Release

    # Create a GitHub Release and upload the MSIX package
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: BookOrca/BookOrca/AppPackages/*.msix
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
